/*******************************************************************************
 * File Name: project.h
 * PSoC Creator  3.1 SP3
 *
 *  Description:
 *  This file is automatically generated by PSoC Creator and should not 
 *  be edited by hand.
 *
 *
 ********************************************************************************
 * Copyright 2008-2013, Cypress Semiconductor Corporation.  All rights reserved.
 * You may use this file only in accordance with the license, terms, conditions, 
 * disclaimers, and limitations in the end user license agreement accompanying 
 * the software package with which this file was provided.
 ********************************************************************************/

#include <cyfitter_cfg.h>
#include <cydevice_trm.h>
#include <cyfitter.h>
#include <cydisabledsheets.h>
#include <NRed.h>
#include <NRed_aliases.h>
#include <NYellow.h>
#include <NYellow_aliases.h>
#include <NGreen.h>
#include <NGreen_aliases.h>
#include <SRed.h>
#include <SRed_aliases.h>
#include <SYellow.h>
#include <SYellow_aliases.h>
#include <SGreen.h>
#include <SGreen_aliases.h>
#include <WRed.h>
#include <WRed_aliases.h>
#include <WYellow.h>
#include <WYellow_aliases.h>
#include <WGreen.h>
#include <WGreen_aliases.h>
#include <ERed.h>
#include <ERed_aliases.h>
#include <EYellow.h>
#include <EYellow_aliases.h>
#include <EGreen.h>
#include <EGreen_aliases.h>
#include <NARed.h>
#include <NARed_aliases.h>
#include <NAYellow.h>
#include <NAYellow_aliases.h>
#include <NAGreen.h>
#include <NAGreen_aliases.h>
#include <SARed.h>
#include <SARed_aliases.h>
#include <SAYellow.h>
#include <SAYellow_aliases.h>
#include <SAGreen.h>
#include <SAGreen_aliases.h>
#include <ESensor.h>
#include <ESensor_aliases.h>
#include <NASensor.h>
#include <NASensor_aliases.h>
#include <TLCMode.h>
#include <TLCMode_aliases.h>
#include <TLCMode1.h>
#include <TLCMode1_aliases.h>
#include <TLCMode2.h>
#include <TLCMode2_aliases.h>
#include <core_cm0_psoc4.h>
#include <core_cm0.h>
#include <CyFlash.h>
#include <CyLib.h>
#include <cyPm.h>
#include <cytypes.h>
#include <cypins.h>
#include <core_cmFunc.h>
#include <core_cmInstr.h>

/*[]*/

